#!/bin/bash
# will lag a machine in via the login window with the credentials supplied via GETOPTS

#Sanity checks
NO_ARGS=0 
E_OPTERROR=85

if [ $# -eq "$NO_ARGS" ]
then
  echo "Usage: `basename $0` options (-u <username> -p <password>)"
  exit $E_OPTERROR          # Exit and explain usage.
fi

while getopts ":u:p:" Option
do
  case $Option in
    u     ) USER=${OPTARG};;
    p     ) PASS=${OPTARG};;
    *     ) echo "Unimplemented option chosen.";;   # Default.
  esac
done

shift $(($OPTIND - 1))

#Close the Bluetooth setup assistant, if there is one
osascript <<EOT
tell application "System Events"
        keystroke "w" using {command down}
end tell
EOT

#Wait a little bit for everything to work
sleep 5

#Type in the username, password, and press return
osascript <<EOT
tell application "System Events" to keystroke "$USER"
tell application "System Events" to delay 2
tell application "System Events" to keystroke tab
tell application "System Events" to delay 2
tell application "System Events" to keystroke "$PASS"
tell application "System Events" to delay 2
tell application "System Events" to keystroke return
EOT

exit $?