#!/bin/bash
# permOpener
# - Blasts permissions wide open
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
VAR=$1
echo "${VAR}"
if [[ $EUID -ne 0 ]]; then
	echo "Must run as root"
	exit 1
else
	if [[ -d "${VAR}" ]]; then
		echo "${VAR} Found"
		diskutil enableOwnership "${VAR}" > /dev/null 2>&1
		chown -Rf _unknown:everyone "${VAR}"
		chmod -R +a "everyone allow list,add_file,search,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" "${VAR}"
		chmod -Rf 777 "${VAR}"
		diskutil disableOwnership "${VAR}" > /dev/null 2>&1
		echo "${VAR} Permissions Fixed"
		exit 0
	else
		echo "${VAR} Not Found and Not Repaired"
		exit 2
	fi
fi