#!/bin/sh
# ccFix_czecNrun
# - checks to make sure we on on a lab machine
# - checks for fixes in F_ixes folder
# - executes each "f_" script
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#Variabls and Tests
TST00="/Volumes/SCA_MacHD/Users/ard"
TST01=`[ "$(ls -A /private/var/root/bin/F_ixes)" ] && echo "NotEmpty" || echo "Empty"`
FIXES="/private/var/root/bin/F_ixes"
LOGF="/private/var/root/cc_maintain.log"
ELF=`basename $0`
TAMP=`date "+%m-%d-%Y %H:%M:%S"`
CA="$ELF : $TAMP : "

cd /

# Make sure we are on an SCA machine, then rm old app and cp new one
if [[ -d "${TST00}" ]]
then
	rm -f /private/var/root/bin/F_ixes/.DS_Store
	if [[ "${TST01}" == "NotEmpty" ]]
	then
		cd /
		for CRIPT in /private/var/root/bin/F_ixes/*
		do
			echo "${CA}Executing : $CRIPT"
			"$CRIPT"
			wait $!
		done
	else
		echo "${CA}No fixes to run."
		exit 0
	fi
else
	echo "${CA}ERROR: This is not an cc maintained machine. No fixes."
	exit 0
fi

echo "${CA}Done executing f_ixes"
exit 0